blog_posts/forms.py
#blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField,FileAllowed 

class BlogPostForm(FlaskForm): 
    title = StringField('Title',validators=[DataRequired()])
    text = TextAreaField('Text',validators=[DataRequired()])
    post_image = FileField('Post an Image',validators=[FileAllowed(['jpg','png'])])
    submit = SubmitField('Post Blog')

blog_posts/views.py
# blog_posts/views.py
from flask import render_template,url_for,flash,request,redirect,Blueprint,abort
from flask_login import current_user,login_required
from Carblog import db
from Carblog.models import BlogPost
from Carblog.blog_posts.forms import BlogPostForm 
from Carblog.blog_posts.picture_handler import add_post_pic 

blog_posts = Blueprint('blog_posts',__name__)

# CREATE

@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():
        if form.post_image.data:
            username = current_user.username
            pic_filename = add_post_pic(form.post_image.data, username)
        else: 
            pic_filename = 'default_post.png'

        blog_post = BlogPost(title=form.title.data,text=form.text.data,post_image=pic_filename, 
                             user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Created', 'success')
        return redirect(url_for('core.index'))
    
    return render_template('create_post.html',form=form)


# BLOG POST VIEW
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,post_image=blog_post.post_image,date=blog_post.date,post=blog_post)


# UPDATE
@blog_posts.route('/<int:blog_post_id>/update',methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()


    if form.validate_on_submit():
        if form.post_image.data:
            username = current_user.username
            pic_filename = add_post_pic(form.post_image.data,username)  
            blog_post.post_image = pic_filename        

        blog_post.title = form.title.data
        blog_post.text = form.text.data
        blog_post.user_id = current_user.id

        db.session.commit()
        flash('Blog Post Updated', 'success')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post_id))
    
    elif request.method == "GET":
        form.title.data = blog_post.title
        form.text.data = blog_post.text 

    post_image = url_for('static', filename='post_pics/' + blog_post.post_image)
    return render_template('create_post.html',title='Update',form=form, post_image=post_image)

    



# DELETE
@blog_posts.route('/<int:blog_post_id>/delete',methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Post Deleted', 'success')
    return redirect(url_for('core.index'))


core/views.py
#core/views.py
from flask import render_template,url_for,flash,redirect,Blueprint
from Carblog import db
from Carblog.models import User,BlogPost
from flask import render_template,request,Blueprint

core = Blueprint('core',__name__)

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('index.html',blog_posts=blog_posts)


@core.route('/info')
def info():
    return render_template('info.html')


users/views.py
#users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint 
from flask_login import login_user, current_user , logout_user, login_required 
from Carblog import db
from Carblog.models import User, BlogPost
from Carblog.users.forms import RegistrationForm, LoginForm,UpdateUserForm, ResetPasswordForm
from Carblog.users.picture_handler import add_profile_pic 
from werkzeug.security import generate_password_hash

users = Blueprint('users',__name__)

# register 
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,username=form.username.data,password=form.password.data,securityQuestion=form.securityQuestion.data,securityAnswer=form.securityAnswer.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))
    return render_template('register.html',form=form)

# login

@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')
            if next is None or not next.startswith('/'):
                next = url_for('core.index')

            return redirect(next)
        else:
            flash('Invalid email or password.', 'danger')

    return render_template('login.html', form=form)





# logout 
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("core.index"))
# account (update UserForm)
@users.route('/account',methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic 

        current_user.username = form.username.data 
        current_user.email = form.email.data
        current_user.securityQuestion = form.securityQuestion.data
        current_user.securityAnswer = form.securityAnswer.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))
    
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email 
        form.securityQuestion.data = current_user.securityQuestion
        form.securityAnswer.data = current_user.securityAnswer

    profile_image = url_for('static',filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)

# user's list of blog posts
@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

 
@users.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    form = ResetPasswordForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data, username=form.username.data).first()

        if user and user.securityQuestion == form.securityQuestion.data and user.securityAnswer.lower() == form.securityAnswer.data.lower():
            user.password_hash = generate_password_hash(form.password.data)
            db.session.commit()
            flash('Your password has been reset successfully.', 'success')
            return redirect(url_for('users.login'))
        else:
            flash('Invalid credentials or security answer.', 'danger')

    return render_template('reset_password.html', form=form)

templates/account.html
{% extends "base.html" %}
{% block content %}

<style>
body {
  background-image: url('https://static1.thegamerimages.com/wordpress/wp-content/uploads/2022/11/Need-For-Speed-Underground-2-Fan-Shows-What-A-Remaster-Could-Look-Like.jpg');
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
}

.login-container {
    max-width: 400px;
    margin: 50px auto;
    padding: 20px;
    background-color: rgba(0, 0, 0, 0.7);
    border-radius: 10px;
    color: #ffc107;
  }

  .form-group {
    margin-bottom: 15px;
  }

  .form-label {
    display: block;
    margin-bottom: 5px;
  }

  .form-control {
    width: 100%;
  }

  .btn {
    width: 100%;
  }
</style>

<div class="jumbotron d-flex flex-column align-items-center justify-content-center text-center">
        <h1 style ="color:gold";> Welcome to the page for {{current_user.username}}</h1>
        <img align='center' src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}" alt="">
</div>



  <div class="login-container">
    <form method="POST" action="" enctype="multipart/form-data">
        {{form.hidden_tag()}} 

      <div class="form-group text-warning">
        {{form.username.label(class="mb-3 text-warning")}}{{form.username(class="form-control bg-dark text-warning")}}
      </div>  
      
      <div class="form-group text-warning">
      {{form.email.label(class="mb-3 text-warning")}}{{form.email(class="form-control bg-dark text-warning")}}
      </div>

      <div class="form-group text-warning">
      {{form.picture.label(class="mb-3 text-warning")}}{{form.picture(class="form-control bg-dark text-warning")}}
      </div>
      <div class="form-group text-warning">
        {{form.securityQuestion.label(class="mb-3 text-warning")}}{{form.securityQuestion(class="form-control bg-dark text-warning")}}
      </div>  
      <div class="form-group text-warning">
        {{form.securityAnswer.label(class="mb-3 text-warning")}}{{form.securityAnswer(class="form-control bg-dark text-warning")}}
      </div>  

      <div class="form-group text-warning">
      {{form.submit(class="btn btn-primary bg-warning")}}
      </div>

    </form>


  </div>
{% endblock %} 

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta charset="UTF-8" />
    <title></title>
    <style>
body {
  background-image: url('https://images.hdqwalls.com/wallpapers/need-for-speed-underground-nissan-350z-ru.jpg');
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
  background-attachment: fixed;
}

</style>
</head>
<body>


<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Need For Speed</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{{url_for('core.index')}}">Home</a>
        <a class="nav-link" href="{{url_for('core.info')}}">About</a>
        {% if current_user.is_authenticated %}
        <a class="nav-link" href="{{url_for('users.logout')}}">Log out</a>
        <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
        <a class="nav-link" href="{{url_for('blog_posts.create_post')}}">Create Post</a>
        {% else %}
        <a class="nav-link" href="{{url_for('users.login')}}">Log in</a>
        <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>    

<div class="container">
    {% block content %}

    {% endblock %}
 
</div>
    
</body>
</html>

templates/blog_post.html
{% extends "base.html" %}
{% block content %}

<div class="card bg-dark">
  <div class="card-body">
    <h1 style ="color:gold";>{{post.title}}</h1>
    <h2 style ="color:rgb(255, 0, 242)";>Written by: {{post.author.username}}</h2>
    <h3 style ="color:rgb(255, 0, 242)";>Published: {{post.date.strftime('%B %d, %y')}}</h3>
    <p style ="color:gold";>{{post.text}}</p>
    <img src="{{ url_for('static', filename='post_pics/' + post.post_image) }}">

  </div>
</div>
    {% if post.author == current_user %}
    <div class="d-flex gap-2 mt-3">
        
      <form action="{{ url_for('blog_posts.update', blog_post_id=post.id) }}" method="get">
        <button type="submit" class="btn btn-danger">Update</button>
      </form>

        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#del_modal">Delete</button>

    </div>
    {% endif %}


</div>
<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document" >
    <div class="modal-content bg-dark">
      <div class="modal-header">
        <h5 class="modal-title" style ="color:gold";>Delete Post?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p style ="color:gold";>Are you sure you want to delete the post?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
       
        <form action="{{url_for('blog_posts.delete_post',blog_post_id=post.id)}}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
        </form>


      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/create_post.html
{% extends "base.html" %}
{% block content %}

<style>
    body {
    background-image: url('https://assetsio.gnwcdn.com/need-for-speed-most-wanted-2005-art.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp');
            }

.login-container {
    max-width: 400px;
    margin: 50px auto;
    padding: 20px;
    background-color: rgba(0, 0, 0, 0.7);
    border-radius: 10px;
    color: #ffc107;
  }

  .form-group {
    margin-bottom: 15px;
  }

  .form-label {
    display: block;
    margin-bottom: 5px;
  }

  .form-control {
    width: 100%;
  }

  .btn {
    width: 100%;
  }
</style>

  <div class="login-container">
    <form class="form-group" method="POST" enctype="multipart/form-data">
        {{form.hidden_tag()}}

        <div class="form-group text-warning">
            {{form.title.label(class="form-control-label bg-dark text-warning")}}
            {{form.title(class="form-control form-control-lg bg-dark text-warning")}}
        <div>
        <div class="mb-3">
            {{form.post_image.label(class="mb-3 text-warning")}}
            {{form.post_image(class="form-control bg-dark text-warning")}}
        </div>  
        <div class="form-group text-warning">
            {{form.text.label(class="form-control-label bg-dark text-warning")}}
            {{form.text(class="form-control form-control-lg bg-dark text-warning")}}
        </div>        
        <div class="form-group">
            {{form.submit(class="btn btn btn-warning")}}
        </div>

    </form>

  </div>


{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron bg-dark">
    <h1 style ="color:gold";><b1>Need for Speed Community Posts</b1></h1>
  </div>

  <div class="container">

    {% for post in blog_posts.items  %}
    <div class = "card bg-warning">
      <div class="card-body">
        <h2> <a class='card-title' href="{{ url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
        <a href="{{url_for('users.user_posts',username=post.author.username)}}" style ="color:rgb(255, 0, 242)">Written By: {{ post.author.username}}</a>
        <p>Published on: {{post.date.strftime('%Y-%m-%d')}}</p>
        <a class="btn btn-danger" href="{{ url_for('blog_posts.blog_post',blog_post_id=post.id)}}">Read Blog Post</a>
      </div>

    </div>

    {% endfor %}

  </div>

  <nav aria-label="Page navigation example">
  <ul class="pagination">
    {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
       {% if blog_posts.page == page_num %}
    <li class="page-item disabled"><a class="page-link bg-danger" href="{{url_for('core.index',page=page_num)}}">Current</a></li>
       {% else %}
    <li class="page-item"><a class="page-link bg-danger" href="{{url_for('core.index',page=page_num)}}" style ="color:white">{{page_num}} </a></li>

       {% endif %}
    {% endfor %}
  </ul>
</nav>


{% endblock %}

templates/info.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <style>
    body {
      background-image: url('https://preview.redd.it/need-for-speed-underground-2-3840x2160-v0-aubav3w9ngm91.png?auto=webp&s=9435b36cff7ecd81adbce2e268249a1726727676');
      background-size: cover;
      background-repeat: no-repeat;
      background-position: center;
     }
  </style>

</div>

<div class="jumbotron bg-dark d-flex flex-column align-items-center justify-content-center text-center">
    <h1 style ="color:gold";>This Era of Need For Speed captured the peak of Car Culture</h1>
</div>

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://media.moddb.com/images/members/5/4517/4516948/profile/Screenshot_2025-07-19_091849.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://i.ytimg.com/vi/K3EnLZH-Nss/maxresdefault.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://nfsmods.xyz/uploads/thumbnails/Archie-354f03e0ca7ff5f87a036b208a5e9ff4.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>



{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
    <style>

.login-container {
    max-width: 400px;
    margin: 50px auto;
    padding: 20px;
    background-color: rgba(0, 0, 0, 0.7);
    border-radius: 10px;
    color: #ffc107;
  }

  .form-group {
    margin-bottom: 15px;
  }

  .form-label {
    display: block;
    margin-bottom: 5px;
  }

  .form-control {
    width: 100%;
  }

  .btn {
    width: 100%;
  }

</style>

<div class="login-container"> 
  <form class="form-group text-bg-dark" method="POST">
    {{form.hidden_tag()}}
    <div class="form-group text-warning">
    {{form.email.label(class="form-label bg-warning text-dark")}}{{form.email(class="form-control bg-dark text-warning", placeholder="Enter email")}}<br>
    </div>
    <div class="form-group text-warning"> 
    {{form.password.label(class="form-label bg-warning text-dark")}}{{form.password(class="form-control bg-dark text-warning",placeholder="Password")}}<br>
    </div>
    {{form.submit(class="btn btn-danger")}}


  </form>
</div>

<div class="login-container">
   <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#del_modal">Reset Password</button>
</div>

<div class="modal" tabindex="-1" role="dialog" id="del_modal">
  <div class="modal-dialog" role="document" >
    <div class="modal-content bg-dark">
      <div class="modal-header">
        <h5 class="modal-title" style ="color:gold";>Reset Password?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p style ="color:gold";>Are you sure you want to reset password</p>
      </div>
      <div class="modal-footer">
       <a href="{{url_for('users.reset_password')}}" class="btn btn-secondary">Reset Password</a>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
       

      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block content %}

<style>
body {
  background-image: url('https://i.ytimg.com/vi/RyfQEf-tHkM/maxresdefault.jpg');
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
}

.login-container {
    max-width: 400px;
    margin: 50px auto;
    padding: 20px;
    background-color: rgba(0, 0, 0, 0.7);
    border-radius: 10px;
    color: #ffc107;
  }

  .form-group {
    margin-bottom: 15px;
  }

  .form-label {
    display: block;
    margin-bottom: 5px;
  }

  .form-control {
    width: 100%;
  }

  .btn {
    width: 100%;
  }

</style>

<div class="login-container">
  <form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group">
    {{form.email.label(class="form-label bg-dark")}}{{form.email(class="form-control bg-dark text-warning", placeholder="Enter email")}}<br>
    </div>
    <div class="form-group">
    {{form.username.label(class="form-label bg-dark")}}{{form.username(class="form-control bg-dark text-warning", placeholder="Enter Username")}}<br>
    </div>
    <div class="form-group">
    {{form.securityQuestion.label(class="form-label bg-dark")}}{{form.securityQuestion(class="form-control bg-dark text-warning", placeholder="Enter recovery question")}}<br>
    </div>
    <div class="form-group">
    {{form.securityAnswer.label(class="form-label bg-dark")}}{{form.securityAnswer(class="form-control bg-dark text-warning", placeholder="Enter recovery answer")}}<br>
    </div>
    <div class="form-group">
    {{form.password.label(class="form-label bg-dark")}}{{form.password(class="form-control bg-dark text-warning", placeholder="Enter Password")}}<br>
    </div>
    {{form.pass_confirm.label(class="form-label bg-dark")}}{{form.pass_confirm(class="form-control bg-dark text-warning", placeholder="Confirm Password")}}<br>
    <div> 
    {{form.submit(class="btn btn-danger")}}
    </div>


  </form>
</div>
{% endblock %}

templates/reset_password.html
{% extends "base.html" %}
{% block content %}

<style>
body {
  background-image: url('https://preview.redd.it/zgfz64t3bov31.jpg?auto=webp&s=e045f6baa394adad47a62613c625b07aa6d78876');
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
}

.login-container {
    max-width: 400px;
    margin: 50px auto;
    padding: 20px;
    background-color: rgba(0, 0, 0, 0.7);
    border-radius: 10px;
    color: #ffc107;
  }

  .form-group {
    margin-bottom: 15px;
  }

  .form-label {
    display: block;
    margin-bottom: 5px;
  }

  .form-control {
    width: 100%;
  }

  .btn {
    width: 100%;
  }

</style>


  <div class="login-container">
    <form method="POST">
        {{form.hidden_tag()}} 
  
      <div class="form-group text-warning">
      {{form.email.label(class="mb-3 text-warning")}}{{form.email(class="form-control bg-dark text-warning")}}
      </div>
      <div class="form-group text-warning">
        {{form.username.label(class="mb-3 text-warning")}}{{form.username(class="form-control bg-dark text-warning")}}
      </div>  
      <div class="form-group text-warning">
        {{form.securityQuestion.label(class="mb-3 text-warning")}}{{form.securityQuestion(class="form-control bg-dark text-warning")}}
      </div>  
      <div class="form-group text-warning">
        {{form.securityAnswer.label(class="mb-3 text-warning")}}{{form.securityAnswer(class="form-control bg-dark text-warning")}}
      </div>
      <div class="form-group text-warning">
        {{form.password.label(class="mb-3 text-warning")}}{{form.password(class="form-control bg-dark text-warning")}}
      </div>    
      <div class="form-group text-warning">
        {{form.pass_confirm.label(class="mb-3 text-warning")}}{{form.pass_confirm(class="form-control bg-dark text-warning")}}
      </div>  
      <div class="form-group text-warning">
      {{form.submit(class="btn btn-primary bg-warning")}}
      </div>

    </form>


  </div>

{% endblock %}

templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="card bg-warning">
  <div class="card-body">
    <div align='center'>
        <h1 style ="color:black";>Blacklist member {{user.username}} </h1>
        <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}">
    </div>

  </div>


{% for post in blog_posts.items %}
  <h2> <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}" style ="color:black">{{post.title}}</a> </h2>
  Written By: <a href="{{url_for('users.user_posts',username=post.author.username)}}" style ="color:rgb(255, 0, 242)">{{post.author.username}}</a>
  <p> Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
  <br>
  <p>{{post.text}}</p>
  <br> 
{% endfor %}
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
       {% if blog_posts.page == page_num %}
    <li class="page-item disabled"><a class="page-link bg-danger" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">Current</a></li>
       {% else %}
    <li class="page-item"><a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{page_num}}</a></li>
       {% endif %}
    {% endfor %}
  </ul>
</nav>


{% endblock %}